### ISSUE TITLE
Support Go Modules

### ISSUE THREAD

**Issue by qcrao** [golang-design/ssaplayground#1]
```golang
package main

import "github.com/cch123/goroutineid"

func main() {
    id := goroutineid.GetGoID()
    println(id) // 1
}
```

输出：

$GOSSAPATH/main.go:3:8: cannot find package "." in:
/app/vendor/github.com/cch123/goroutineid

**Comment by changkun** [comment]
Go Modules is supported now. 

See an example here: https://changkun.de/gossa?id=3cf5fa2e-fb54-46d8-97a5-31f8c2604a72

**Comment by changkun** [comment]
Note that your code snippet remains to fail because of an issue in https://github.com/cch123/goroutineid/issues/2.
