### ISSUE TITLE
proposal: record build history

### ISSUE THREAD

**Issue by yangwenmai** [golang-design/ssaplayground#3]
当我执行 build 后会产生一个新的 ssa URL，最好可以将这个记录下来。

或者可以做上下切分，然后进行对比。

**Comment by changkun** [comment]
为什么不开启两个 tab？

**Comment by yangwenmai** [comment]
> 为什么不开启两个 tab？

是一个解决办法。

**Comment by changkun** [comment]
根据你的描述，是一个前端 UI 层面的需求，包括许多布局设计细节等问题，这些要求并不明确。
此外，比较两份不同的 SSA 更正确的做法似乎并不常见，我们更关心的其实是 SSA IR 的中间变换。故考虑这个可能是个伪需求，可能不会实现。

留下一天时间发表反对意见。

**Comment by changkun** [comment]
No changes in consensus. Close.
