### ISSUE TITLE
add anonymous function support

### ISSUE THREAD

**Issue by katsusan** [golang-design/ssaplayground#5]
https://github.com/golang-design/ssaplayground/blob/84af6584d342c9f67b54435833223f2fff4509d3/public/main.js#L33-L36

Currently `'func '+funcname` cannot cover the case of anonymous functions. 
Eg, in following code `func() {x++}` can be resolved by GOSSAFUNC=main.func1.

```Go
func main() {
	var x int
	go func() {
		x++
	}()
}
```
And there are more complicated cases (such as nested anonymous  functions),
I think before further code analysis is integrated in frontend, it's better to temporarily remove this.

**Comment by katsusan** [comment]
By contrast, gcflags cant be limited to very few options(-N, -l, -B, -race, -wb, ...), which seems not filted by frontend.

**Comment by changkun** [comment]
Sounds like a valid reason. PR welcome.
